### ISSUE TITLE
problem with building the app

### ISSUE THREAD

**Issue by bharath79** [chaquo/chaquopy-hello#10]
![Untitled](https://user-images.githubusercontent.com/48067189/57599537-a49e3a80-7574-11e9-844a-53248a797cb5.jpg)
the main java file isn't building up

**Comment by mhsmith** [comment]
It looks like you don't have Python installed on the build machine. I suggest you install the current version from python.org. 

For more details, see the documentation [here](https://chaquo.com/chaquopy/doc/current/android.html#development).

**Comment by bharath79** [comment]
i've uncommented the buildPath in grade and set it to my anaconda
directory.

**Comment by mhsmith** [comment]
And does it work? If not, please show exactly what you've done.

**Comment by bharath79** [comment]
after uncommenting the buildPath and setting it to my anaconda directory. the app gets deployed and runs smoothly on the emulator. but the xml still has that error

**Comment by bharath79** [comment]
the app gets deployed in the emulator. but the xml file still has that
error (.MainActivity)

**Comment by mhsmith** [comment]
OK, the error indication in the IDE is probably harmless, it's just happening because MainActivity.java is being generated in an unusual way.

**Comment by bharath79** [comment]
can you link me to tutorial or sources.From where i can learn more about it.
thanks in advanced

**Comment by mhsmith** [comment]
The documentation is all [here](https://chaquo.com/chaquopy/doc/current/).
