### ISSUE TITLE
How to fixed error.please help. Thx

### ISSUE THREAD

**Issue by 1amDonut** [chaquo/chaquopy-hello#11]
ERROR: Cause: debug: python.version not set: you may want to add it to defaultConfig.

**Comment by mhsmith** [comment]
You're using an old version of Chaquopy. Please upgrade to the current version, 6.2.1, as shown in [this project's build.gradle file](https://github.com/chaquo/chaquopy-hello/blob/master/build.gradle).

If you were following instructions from somewhere, please let me know where you found them so I can get them updated.
