### ISSUE TITLE
how to set module path

### ISSUE THREAD

**Issue by Saint-Theana** [chaquo/chaquopy-hello#14]
is that possible to add module path manually?

**Comment by mhsmith** [comment]
Yes, you can add any directory you want to `sys.path`, just like with regular Python.

**Comment by Saint-Theana** [comment]
it does not work.

**Comment by Saint-Theana** [comment]
only when I put file in app.zip that it worked.but it's not what I wanted

**Comment by Saint-Theana** [comment]
it seems no matter module file exist in sys.path or not,as long as app.zip does not contain a same named module file,it always  raises ModuleNotFoundException

**Comment by Saint-Theana** [comment]
I am not good at python,I found importer.py very hard to read,so if nobody solve that problem,I have no choice but gave it up.

**Comment by mhsmith** [comment]
I may be able to help you if you give more specific details, such as:
* what directory are you adding to sys.path?
* what is contained in that directory?
* what import statement are you using?
* what exception and stack trace are you receiving?
