### ISSUE TITLE
How can i call the android java method from Python script

### ISSUE THREAD

**Issue by VPrasannakumar** [chaquo/chaquopy-hello#17]
I am able to run the python script from the android, but I want to know how python will call android methods. Please help me for this.

Thank you in advance.

**Comment by mhsmith** [comment]
See [the documentation](https://chaquo.com/chaquopy/doc/current/python.html) and [these examples](https://github.com/chaquo/chaquopy/blob/master/app/src/main/python/chaquopy/demo/ui_demo.py).
