### ISSUE TITLE
No python interpreter configured for the module

### ISSUE THREAD

**Issue by natalyayyad** [chaquo/chaquopy-hello#18]
After setting up Chaquopy,  I encountered message "No python interpreter configured in the module".  I installed Python Community Edition plugin too. 

![image](https://user-images.githubusercontent.com/47296228/90734882-0308ab80-e2d6-11ea-8fed-1ff358835384.png)

Build.gradle (app)

![image](https://user-images.githubusercontent.com/47296228/90736181-52e77280-e2d6-11ea-9eca-d535a890c9ee.png)

How can I add python interpreter to the project?

**Comment by mhsmith** [comment]
As [the documentation](https://chaquo.com/chaquopy/doc/current/android.html#android-studio-plugin) says, this message is harmless.
