### ISSUE TITLE
Gradle error can not be fixed. Please help.

### ISSUE THREAD

**Issue by hushanhsiang** [chaquo/chaquopy-hello#4]
How to fix this Gradle error as below picture?
https://images2.imgbox.com/9f/b9/gsYRBtDq_o.png

To generate it must follow below step by step otherwise it will not happen:
1. Unzip "chaquopy-hello-master.zip" to a fresh new folder
2. Import "chaquopy-hello-master" project of this folder by Android Studio
3. Put chaquopy-licence key in local-properties of this project
4. Put an pip error in build-gradle(Module, app) as below:
`        python {
            // If "python" is not on your PATH, enable and edit the following line to point to
            // a Python 2.7 or 3.3+ executable.
            // buildPython "C:/Python27/python.exe"

            // This is the version of Python to build into your app. Options are 2.7.14 and 3.6.3.
            version "3.6.3"

            staticProxy "hello"
            pip {
               requests
            }
        }` 
5. Run it and got above Gradle error (the Picture link)
6. Correct the pip error: 
``        python {
            // If "python" is not on your PATH, enable and edit the following line to point to
            // a Python 2.7 or 3.3+ executable.
            // buildPython "C:/Python27/python.exe"

            // This is the version of Python to build into your app. Options are 2.7.14 and 3.6.3.
            version "3.6.3"

            staticProxy "hello"
            pip {
               install "requests"
            }
        }` `
6. The Gradle Error never be fixed, 
I have no idea to fix this Error, I don't know whether it's a Chaquopy bug or my poor Android Studio knowledge.
If you have correct pip instruction in the first edit, it will never happen even you modify the correct pip instruction to a wrong instruction which is like above first code.
Please help, thanks

**Comment by mhsmith** [comment]
After a failed Gradle sync, you must sync again after fixing the problem. Usually Android Studio will prompt you to do this by showing a yellow bar at the top of the screen. If for some reason the bar doesn't appear, it can also be done using Tools > Android > Sync Project with Gradle Files.

**Comment by hushanhsiang** [comment]
It's fixed by "Tools > Android > Sync Project with Gradle Files."
Thank you very much....
