### ISSUE TITLE
Got problem while 'pip install "face_recognition"' 

### ISSUE THREAD

**Issue by hushanhsiang** [chaquo/chaquopy-hello#6]
To install "face_recognition" package on my PC (Windows10) is no problem but I got a problem when I put "install face_recognition" in build.gradel (Module:app) as below.
pip{
                install "requests"
                install "face_recognition"
            }

Error message:
Error:Execution failed for task ':app:generateDebugPythonRequirements'.
> Process 'command 'python'' finished with non-zero exit value 1

To remove 'install "face_recognition"' will be OK but I'd like to use face_recongnition to run my project.
Is it possible to install this package with Chaquopy? Thanks.

**Comment by mhsmith** [comment]
When reporting build errors, please include the details of the error from the "Gradle console" tool window.

**Comment by hushanhsiang** [comment]
Below is the Gradle console:
`Executing tasks: [:app:generateDebugSources, :app:generateDebugAndroidTestSources, :app:mockableAndroidJar]

Configuration on demand is an incubating feature.
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:checkDebugManifest UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:extractPythonBuildPackages UP-TO-DATE
:app:generateDebugPythonRequirements
Installing for armeabi-v7a
Collecting requests
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting face_recognition
  Using cached face_recognition-1.0.0-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests)
  Using cached certifi-2017.11.5-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests)
  Using cached urllib3-1.22-py2.py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests)
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting numpy (from face_recognition)
  Using cached https://chaquo.com/pypi/numpy/numpy-1.9.2-cp36-cp36m-android_15_armeabi_v7a.whl
Collecting face-recognition-models>=0.2.0 (from face_recognition)

  Cache entry deserialization failed, entry ignored
  Could not find a version that satisfies the requirement face-recognition-models>=0.2.0 (from face_recognition) (from versions: 0.1.3)
No matching distribution found for face-recognition-models>=0.2.0 (from face_recognition) (NOTE: Chaquopy only supports wheels, not sdist packages)
Exit status 1

:app:generateDebugPythonRequirements FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:generateDebugPythonRequirements'.
> Process 'command 'python'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s

7 actionable tasks: 1 executed, 6 up-to-date
`

**Comment by hushanhsiang** [comment]
Same code but seems got different Error of "Gradle console":
`Executing tasks: [:app:generateDebugSources, :app:generateDebugAndroidTestSources, :app:mockableAndroidJar]

Configuration on demand is an incubating feature.
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:checkDebugManifest UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:extractPythonBuildPackages UP-TO-DATE
:app:generateDebugPythonRequirements
Installing for armeabi-v7a
Collecting requests
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting face_recognition
  Using cached face_recognition-1.0.0-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests)
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests)
  Using cached certifi-2017.11.5-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests)
  Using cached urllib3-1.22-py2.py3-none-any.whl
Collecting numpy (from face_recognition)
  Using cached https://chaquo.com/pypi/numpy/numpy-1.9.2-cp36-cp36m-android_15_armeabi_v7a.whl
Collecting dlib>=19.5 (from face_recognition)

  Could not find a version that satisfies the requirement dlib>=19.5 (from face_recognition) (from versions: )
No matching distribution found for dlib>=19.5 (from face_recognition) (NOTE: Chaquopy only supports wheels, not sdist packages)
Exit status 1

:app:generateDebugPythonRequirements FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:generateDebugPythonRequirements'.
> Process 'command 'python'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s

7 actionable tasks: 1 executed, 6 up-to-date
`

**Comment by mhsmith** [comment]
This issue was moved to chaquo/chaquopy#24

**Comment by mhsmith** [comment]
Since you're no longer having trouble with this app specifically, please report future issues in the other project.
