### ISSUE TITLE
subprocess permission denied

### ISSUE THREAD

**Issue by sunorr** [chaquo/chaquopy-hello#8]
When I call subprocess.Popen in python code，get this error:
`com.chaquo.python.PyException: OSError: [Errno 13] Permission denied
        at <python>._execute_child(stdlib/subprocess.py:1047)
        at <python>.__init__(stdlib/subprocess.py:394)`
Which kind of permission should I get in Android system?

**Comment by mhsmith** [comment]
What program are you trying to execute?

Are there any other relevant messages in the logcat?

**Comment by sunorr** [comment]
This is my own mistake, I executed a command without execute permission.
Thanks for the reply.
